### ISSUE TITLE
Remove compiler warnings

### ISSUE THREAD

**Issue by panzone** [panzone/crypto-chapel#13]
chapel-lang/chapel@b50d504 introduces a warning for partially solving the problem of including a file module instead of an internal module. However, because of the structure of crypto-chapel, we trigger this warning each time. We should refactor the library in a way to avoid this warning.

This also should presents the side effect of removing the necessity of using a double "use" in this library.

**Comment by saru95** [comment]
Would building crypto-chapel using the latest Chapel-Lang code reflect this warning?

**Comment by saru95** [comment]
https://github.com/panzone/crypto-chapel/pull/17/commits/1ef1c5fdd28e9ce48e02eac15b452b6c6aa01d56 solves this.

**Comment by panzone** [comment]
Merged.
