### ISSUE TITLE
KDF module makes deadend code fails

### ISSUE THREAD

**Issue by panzone** [panzone/crypto-chapel#9]
The current structure of the KDF module will make fail the compiler if the module is used. This is probably caused by the use of Crypto inside the module but this is necessary because of the Hash argument of PBKDF2.

Since it's kinda weird that KDF has its own module, the best solution is probably convert KDF to a class into the Crypto module. If a class is to be used, it should be discuss if the hash algorithm must be passed during construction or not.

**Comment by saru95** [comment]
https://github.com/panzone/crypto-chapel/pull/11 fixes this.
